### ISSUE TITLE
No admin options under Jack or Igor

### ISSUE THREAD

**Issue by ADBeasley** [my17560/dokuwiki-template-readthedokus#69]
I was testing a Docker install (Debian 11 x86 box) with the following compose file:

```
version: "2.1"
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/DocuWiki/:/config
    ports:
      - 80:80
      - 443:443 #optional
    restart: unless-stopped
```

Logged in and ran the set up configuration for the admin user.
Restarted the container.
Downloaded the template and applied it as the active one.

Started a new web session but just got the basic page contents showing the fact that the start page had not been created. There was no header / footer showing - the 'bread crumb' trail just showed 'docs and start'. 

Using the admin link directly on the second session (.../doku.php?id=start&do=admin) did not work

Changing back to the default template allowed access to the footer / log in options etc as expected.

EDIT:

Created a new container with image: lscr.io/linuxserver/dokuwiki:2022-07-31a-ls158

System reports I am now on Release 2022-07-31a "Igor" 

Setting the template to be Read the Dokus just gives me:

<img width="780" alt="Screenshot 2023-06-16 at 12 35 21" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/39886283/660996ad-1b99-4905-a112-3b5f61681eb9">
